version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
  redis:
    image: redis
  frontend:
    image: frontend
  backend:
    restart: unless-stopped
    image: backend
    expose:
      - "8000"
    environment: 
      - REDIS=redis
      - DB_USERNAME=docker
      - DB_PASSWORD=docker
      - DB_HOST=database
