version: '3.5'

services:

  frontend:
    image: ex1.12_front
    ports:
      - 5000:5000

  backend:
    image: ex1.12_back
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=docker
      - DB_NAME=docker
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    container_name: db_container
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
